version: '3.8'

services:
  fastapi:
    build:
      context: .  # Use the current directory as the context
    container_name: fastapi-container
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: fastapi-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi