name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug runner environment
        run: |
          echo "Runner OS: $(uname -a)"
          cho "SSH version: $(ssh -V)"