name: CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔹 Navigating to deployment directory..."
            cd ~/fastapi-book-project || mkdir ~/fastapi-book-project && cd ~/fastapi-book-project

            echo "🔹 Fetching latest code from GitHub..."
            if [ -d ".git" ]; then
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/gg243/fastapi-book-project.git .
            fi

            echo "🔹 Building Docker container on the server..."
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker build -t fastapi-app .

            echo "🔹 Starting new container..."
            docker run -d --name fastapi-container -p 8000:8000 --restart=always fastapi-app

            echo "✅ Deployment successful!"



      

